### ISSUE TITLE
SDG: link to discussion page

### ISSUE THREAD

**Issue by ofrancon** [Project-Resilience/platform#46]
For each SDG, add a link to its discussion page in a `Discussion` section below the `Proposals` one.

**Comment by Steven-Birkinbine** [comment]
Happy to take this one. Unable to assign to myself as I do not have collaborator access

**Comment by ofrancon** [comment]
> Happy to take this one. Unable to assign to myself as I do not have collaborator access

@Steven-Birkinbine sent you an invite. Thanks for taking this one!

**Comment by ofrancon** [comment]
@CelestialCthulhu the commits look good, thanks! Can you create a branch and a Pull Request so we can merge them?

**Comment by Steven-Birkinbine** [comment]
@ofrancon All 13 commits, for the 17 SDGs, should be contained in the branch 46-sdg-link-to-discussion-page for your review.
